/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedCardapiosRouteImport } from './routes/_authenticated/cardapios'
import { Route as AuthenticatedCensoRouteImport } from './routes/_authenticated/censo'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedEscalaAdministrativaRouteImport } from './routes/_authenticated/escala-administrativa'
import { Route as AuthenticatedEscalaEnfermagemRouteImport } from './routes/_authenticated/escala-enfermagem'
import { Route as AuthenticatedEscalaTecnicaRouteImport } from './routes/_authenticated/escala-tecnica'
import { Route as AuthenticatedExamesRouteImport } from './routes/_authenticated/exames'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPeriodosRouteImport } from './routes/_authenticated/periodos'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPlantaoRouteImport } from './routes/_authenticated/plantao'
import { Route as AuthenticatedSaidasRouteImport } from './routes/_authenticated/saidas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAvaliacaoIdRouteImport } from './routes/_authenticated/avaliacao.$id'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedPiaIndexRouteImport } from './routes/_authenticated/pia.index'
import { Route as AuthenticatedPiaIdRouteImport } from './routes/_authenticated/pia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardapiosRoute = AuthenticatedCardapiosRouteImport.update({
  id: '/cardapios',
  path: '/cardapios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCensoRoute = AuthenticatedCensoRouteImport.update({
  id: '/censo',
  path: '/censo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaAdministrativaRoute =
  AuthenticatedEscalaAdministrativaRouteImport.update({
    id: '/escala-administrativa',
    path: '/escala-administrativa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscalaEnfermagemRoute =
  AuthenticatedEscalaEnfermagemRouteImport.update({
    id: '/escala-enfermagem',
    path: '/escala-enfermagem',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscalaTecnicaRoute =
  AuthenticatedEscalaTecnicaRouteImport.update({
    id: '/escala-tecnica',
    path: '/escala-tecnica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamesRoute = AuthenticatedExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeriodosRoute = AuthenticatedPeriodosRouteImport.update({
  id: '/periodos',
  path: '/periodos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantaoRoute = AuthenticatedPlantaoRouteImport.update({
  id: '/plantao',
  path: '/plantao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaidasRoute = AuthenticatedSaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvaliacaoIdRoute =
  AuthenticatedAvaliacaoIdRouteImport.update({
    id: '/avaliacao/$id',
    path: '/avaliacao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPiaIndexRoute = AuthenticatedPiaIndexRouteImport.update({
  id: '/pia/',
  path: '/pia/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiaIdRoute = AuthenticatedPiaIdRouteImport.update({
  id: '/pia/$id',
  path: '/pia/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cardapios': typeof AuthenticatedCardapiosRoute
  '/censo': typeof AuthenticatedCensoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/escala-administrativa': typeof AuthenticatedEscalaAdministrativaRoute
  '/escala-enfermagem': typeof AuthenticatedEscalaEnfermagemRoute
  '/escala-tecnica': typeof AuthenticatedEscalaTecnicaRoute
  '/exames': typeof AuthenticatedExamesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/plantao': typeof AuthenticatedPlantaoRoute
  '/saidas': typeof AuthenticatedSaidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/avaliacao/$id': typeof AuthenticatedAvaliacaoIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/pia/$id': typeof AuthenticatedPiaIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/pia/': typeof AuthenticatedPiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cardapios': typeof AuthenticatedCardapiosRoute
  '/censo': typeof AuthenticatedCensoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/escala-administrativa': typeof AuthenticatedEscalaAdministrativaRoute
  '/escala-enfermagem': typeof AuthenticatedEscalaEnfermagemRoute
  '/escala-tecnica': typeof AuthenticatedEscalaTecnicaRoute
  '/exames': typeof AuthenticatedExamesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/plantao': typeof AuthenticatedPlantaoRoute
  '/saidas': typeof AuthenticatedSaidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/avaliacao/$id': typeof AuthenticatedAvaliacaoIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/pia/$id': typeof AuthenticatedPiaIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/pia': typeof AuthenticatedPiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/cardapios': typeof AuthenticatedCardapiosRoute
  '/_authenticated/censo': typeof AuthenticatedCensoRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/escala-administrativa': typeof AuthenticatedEscalaAdministrativaRoute
  '/_authenticated/escala-enfermagem': typeof AuthenticatedEscalaEnfermagemRoute
  '/_authenticated/escala-tecnica': typeof AuthenticatedEscalaTecnicaRoute
  '/_authenticated/exames': typeof AuthenticatedExamesRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/periodos': typeof AuthenticatedPeriodosRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/plantao': typeof AuthenticatedPlantaoRoute
  '/_authenticated/saidas': typeof AuthenticatedSaidasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/avaliacao/$id': typeof AuthenticatedAvaliacaoIdRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/pia/$id': typeof AuthenticatedPiaIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/pia/': typeof AuthenticatedPiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/avisos'
    | '/cardapios'
    | '/censo'
    | '/escala'
    | '/escala-administrativa'
    | '/escala-enfermagem'
    | '/escala-tecnica'
    | '/exames'
    | '/news'
    | '/painel'
    | '/periodos'
    | '/permissoes'
    | '/plantao'
    | '/saidas'
    | '/usuarios'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/avaliacao/$id'
    | '/chat/$threadId'
    | '/pia/$id'
    | '/chat/'
    | '/pia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/avisos'
    | '/cardapios'
    | '/censo'
    | '/escala'
    | '/escala-administrativa'
    | '/escala-enfermagem'
    | '/escala-tecnica'
    | '/exames'
    | '/news'
    | '/painel'
    | '/periodos'
    | '/permissoes'
    | '/plantao'
    | '/saidas'
    | '/usuarios'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/avaliacao/$id'
    | '/chat/$threadId'
    | '/pia/$id'
    | '/chat'
    | '/pia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/avisos'
    | '/_authenticated/cardapios'
    | '/_authenticated/censo'
    | '/_authenticated/escala'
    | '/_authenticated/escala-administrativa'
    | '/_authenticated/escala-enfermagem'
    | '/_authenticated/escala-tecnica'
    | '/_authenticated/exames'
    | '/_authenticated/news'
    | '/_authenticated/painel'
    | '/_authenticated/periodos'
    | '/_authenticated/permissoes'
    | '/_authenticated/plantao'
    | '/_authenticated/saidas'
    | '/_authenticated/usuarios'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/_authenticated/avaliacao/$id'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/pia/$id'
    | '/_authenticated/chat/'
    | '/_authenticated/pia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapios': {
      id: '/_authenticated/cardapios'
      path: '/cardapios'
      fullPath: '/cardapios'
      preLoaderRoute: typeof AuthenticatedCardapiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/censo': {
      id: '/_authenticated/censo'
      path: '/censo'
      fullPath: '/censo'
      preLoaderRoute: typeof AuthenticatedCensoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala-administrativa': {
      id: '/_authenticated/escala-administrativa'
      path: '/escala-administrativa'
      fullPath: '/escala-administrativa'
      preLoaderRoute: typeof AuthenticatedEscalaAdministrativaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala-enfermagem': {
      id: '/_authenticated/escala-enfermagem'
      path: '/escala-enfermagem'
      fullPath: '/escala-enfermagem'
      preLoaderRoute: typeof AuthenticatedEscalaEnfermagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala-tecnica': {
      id: '/_authenticated/escala-tecnica'
      path: '/escala-tecnica'
      fullPath: '/escala-tecnica'
      preLoaderRoute: typeof AuthenticatedEscalaTecnicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exames': {
      id: '/_authenticated/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof AuthenticatedExamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/periodos': {
      id: '/_authenticated/periodos'
      path: '/periodos'
      fullPath: '/periodos'
      preLoaderRoute: typeof AuthenticatedPeriodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantao': {
      id: '/_authenticated/plantao'
      path: '/plantao'
      fullPath: '/plantao'
      preLoaderRoute: typeof AuthenticatedPlantaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saidas': {
      id: '/_authenticated/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof AuthenticatedSaidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avaliacao/$id': {
      id: '/_authenticated/avaliacao/$id'
      path: '/avaliacao/$id'
      fullPath: '/avaliacao/$id'
      preLoaderRoute: typeof AuthenticatedAvaliacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pia/': {
      id: '/_authenticated/pia/'
      path: '/pia'
      fullPath: '/pia/'
      preLoaderRoute: typeof AuthenticatedPiaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pia/$id': {
      id: '/_authenticated/pia/$id'
      path: '/pia/$id'
      fullPath: '/pia/$id'
      preLoaderRoute: typeof AuthenticatedPiaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCardapiosRoute: typeof AuthenticatedCardapiosRoute
  AuthenticatedCensoRoute: typeof AuthenticatedCensoRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedEscalaAdministrativaRoute: typeof AuthenticatedEscalaAdministrativaRoute
  AuthenticatedEscalaEnfermagemRoute: typeof AuthenticatedEscalaEnfermagemRoute
  AuthenticatedEscalaTecnicaRoute: typeof AuthenticatedEscalaTecnicaRoute
  AuthenticatedExamesRoute: typeof AuthenticatedExamesRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPeriodosRoute: typeof AuthenticatedPeriodosRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedPlantaoRoute: typeof AuthenticatedPlantaoRoute
  AuthenticatedSaidasRoute: typeof AuthenticatedSaidasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAvaliacaoIdRoute: typeof AuthenticatedAvaliacaoIdRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedPiaIdRoute: typeof AuthenticatedPiaIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedPiaIndexRoute: typeof AuthenticatedPiaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCardapiosRoute: AuthenticatedCardapiosRoute,
  AuthenticatedCensoRoute: AuthenticatedCensoRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedEscalaAdministrativaRoute:
    AuthenticatedEscalaAdministrativaRoute,
  AuthenticatedEscalaEnfermagemRoute: AuthenticatedEscalaEnfermagemRoute,
  AuthenticatedEscalaTecnicaRoute: AuthenticatedEscalaTecnicaRoute,
  AuthenticatedExamesRoute: AuthenticatedExamesRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPeriodosRoute: AuthenticatedPeriodosRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedPlantaoRoute: AuthenticatedPlantaoRoute,
  AuthenticatedSaidasRoute: AuthenticatedSaidasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAvaliacaoIdRoute: AuthenticatedAvaliacaoIdRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedPiaIdRoute: AuthenticatedPiaIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedPiaIndexRoute: AuthenticatedPiaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
